#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/astra

DAEMON=astra
ASTRA_ARGS=""

[ "$LISTEN_ADDRESS" != "" ] && ASTRA_ARGS="${ASTRA_ARGS} -a ${LISTEN_ADDRESS}"
[ "$LOCAL_ADDRESS" != "" ] && ASTRA_ARGS="${ASTRA_ARGS} -i ${LOCAL_ADDRESS}"
[ "$PORT" != "" ] && ASTRA_ARGS="${ASTRA_ARGS} -p ${PORT}"

PID=$(get_pid $DAEMON)

case "$1" in
    start)
        stat_busy "Starting $DAEMON"
        [ -z "$PID" ] && $DAEMON -d $ASTRA_ARGS &> /dev/null
        if [ $? = 0 ]; then
            add_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    stop)
        stat_busy "Stopping $DAEMON"
        [ -n "$PID" ] && kill $PID #&>/dev/null
        if [ $? = 0 ]; then
            rm_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac
